version: 2
# 빌드 작업을 수행한 job을 작성해 넣는다.
jobs:
  # job의 이름이다. build가 아니어도 상관없다. 아래의 workflows에서 실행할 때 사용된다. 
  build:
    # 위에 언급한대로, 렌탈할 서버를 선택하는 부분이다. 
    # docker 가상화 이미지를 설정할 수 있는데, 
    # circleci에서 미리 빌드해놓은 제공된 이미지 목록에서 선택해야 한다.
    # 다음의 주소에서 선택할 수 있는 이미지를 확인할 수 있다. https://circleci.com/docs/2.0/circleci-images/
    docker:        
    # npm 빌드를 해야하므로, nodejs로 설정했다.
    - image: circleci/node:latest
    steps:
    # 배포할 때 사용할 쉘 스크립트를 step별로 입력한다.
    # 소스를 checkout 하여, 리눅스 머신에 소스를 적용한다.
    - checkout
    # 의존성 설치
    - run: npm install
    # vue 빌드
    - run: npm run build
    # nginx 서버로 포팅 (참고로 이 접속정보는 없다.)
    - run: $ scp -r dist/. testuser@dkant.net:/usr/share/nginx/html/ 

version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test